language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mogy' ]; then cd .. && eval "mv $currentfolder generator-mogy" && cd generator-mogy; fi
